import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useState, useRef } from "react";
import useSWR from "swr";

const fetcher = (...args) => fetch(...args).then((res) => res.json());

export default function Home() {
  const [century, setCentury] = useState(null);
  const inputEl = useRef(null);
  const { data, error } = useSWR(
    !century
      ? "https://www.rijksmuseum.nl/api/nl/collection?key=yW6uq3BV"
      : `https://www.rijksmuseum.nl/api/nl/collection?key=yW6uq3BV${
          "&&f.dating.period=" + century
        }`,
    fetcher
  );

  return (
    <div className={styles.container}>
      <Head>
        <title>museum filter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.header}>MUSEUM</div>

      <main className={styles.main}>
        <h2> Century (1-21)</h2>
        <div className={styles.century}>
          <input
            ref={inputEl}
            className={styles.input}
            placeholder="Century"
            onChange={(e) => {
              if (Number(e.target.value) > 21 || Number(e.target.value) < 0) {
                setCentury(null);
                alert("must be 1-21");
              } else {
                setCentury(e.target.value);
              }
            }}
            type="number"
            min="1"
            max="21"
          ></input>
          <button
            className={styles.button}
            onClick={() => {
              inputEl.current.value = "";
              setCentury(null);
            }}
          >
            clear
          </button>
        </div>
        {error ? (
          <h1>Failed to load</h1>
        ) : !data ? (
          <h1>Loading...</h1>
        ) : (
          <div className={styles.grid}>
            {data.artObjects.map((p) => (
              <div key={p.id} className={styles.images}>
                {p.hasImage ? (
                  <Image
                    src={p.webImage.url}
                    alt={p.longTitle}
                    width={398}
                    height={398}
                  />
                ) : (
                  <div className={styles.withoutImage}>No image available</div>
                )}

                <div>
                  <div className={styles.title}>{p.title}</div>
                  <div className={styles.author}>{p.principalOrFirstMaker}</div>
                </div>
              </div>
            ))}
          </div>
        )}
      </main>
      <footer className={styles.footer}>museum showcase</footer>
    </div>
  );
}
